### ISSUE TITLE
Why do we need Sudo permission while using libfreenect2?

### ISSUE THREAD

**Issue by whatisor** [OpenKinect/libfreenect2#534]
Hi,
Run ./bin/Protonect requires sudo.
Using libfreenect2 for my project also requires sudo.
It is abnormal. Is it possible to make it same with libfreenect (kinect 1)?
Thank you

**Comment by xlz** [comment]
You are never asked to use sudo. It is likely you did not follow the instructions https://github.com/OpenKinect/libfreenect2#protonect-complains-about-no-device-connected-or-failure-opening-device

**Comment by whatisor** [comment]
Perfect!
Thank you.
Can you add it into install script?

**Comment by de-vri-es** [comment]
Installing cross-platform udev rules might be somewhat tricky. For example, on some systems TAG+="uaccess" could be preferred over MODE="0666". I'm also not certain if udev rules go to the same directory on all platforms and distros. If the install script would installs udev rules, it would be nice to be able atleast add an option to disable it so that packagers can use the appropriate rules for their platform.

**Comment by xlz** [comment]
The provided udev rules are clearly not intended for all distros. Debian usually has `GROUP="plugdev" MODE="0664"`. Distro packagers should add their own udev rules as they see fit.
