### ISSUE TITLE
[Question] Is it possible to visualize raw data using OpenGL ?

### ISSUE THREAD

**Issue by moonsh** [OpenKinect/libfreenect2#695]
Hello . 

I would like to visualize raw data which is got from Libfreenect2 using OpenGL.

Therefore, I was trying to include Freeglut but it was failed. 

My goal is visualizing raw data x,y and z as vertexes at OpenGl screen in real time.

Thank you.

**Comment by robozo** [comment]
probably a lot easier to use glfw rather than glut.
would advise getting Protonect.cpp example to compile, then look at viewer.cpp which uses glfw.
replace this with your functions using glDrawArrays(GL_POINTS, ...) or whatever.  works great.

the problem with glut is it wants to run an event loop, so do the libfreenect2 "listeners".
good luck!

**Comment by moonsh** [comment]
Thanks for advice.  I will try .
