### ISSUE TITLE
LED does not always turn off?

### ISSUE THREAD

**Issue by svenevs** [OpenKinect/libfreenect2#958]
`git log -1 --oneline`: [`05beb27`](https://github.com/OpenKinect/libfreenect2/commit/05beb277bb4018ff25a24c90beec8949b09a2ac9) windows: Build upstream libusb only

(sorry, I mis-hit the enter key)

The protonect application reliably turns off the little white xbox LED, all that happens in Protonect is `dev->stop()` followed by a `dev->close()`.  In my own application, the red lights always turn off but sometimes the white light stays on.

I feel like it's because maybe something hasn't gone out of scope (e.g., the packet pipeline) or something.  Does anybody know what would cause this to happen?  Thanks for any suggestions!

**Update**: hmm. It seems Protonect does not always turn off the white LED either...

**Comment by xlz** [comment]
I don't know exactly. My best guess is the white LED indicates if the Kinect's ARM board is running. As long as it is not emitting IR I think this is okay for the sensors. I mean, how do you communicate with the Kinect if it is powered off?

We don't know anything at the protocol level about controlling the LEDs per se. We do use a ShutdownCommand only on Mac https://github.com/OpenKinect/libfreenect2/blob/ec47090673b7d940741dace33e4d4fbe0b32e265/src/libfreenect2.cpp#L972 for some issue. We don't know what exactly this command does though. I think the reason it is not used on other platforms is because "this command actually reboots the device and makes it disappear for 3 seconds" (so it's probably better named RebootCommand) and we want that Protonect can restart instantly.

**Comment by svenevs** [comment]
LOL yeah rebooting by default is best left only to when it's needed!

> I mean, how do you communicate with the Kinect if it is powered off?

I think it's always on if it's plugged in, regardless of the white LED.  If you leave it plugged in but don't do anything with it, no LEDs on, etc, it still generates heat.  I wouldn't be surprised if the terms and conditions allow the video feed to be activated at any time (paranoid)...

Anyway, I agree -- this shouldn't be harfmul to the device and it kind of looks cool.  Thanks for the response :)
